apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logai-agent
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: logai-agent
  template:
    metadata:
      labels:
        app: logai-agent
    spec:
      hostNetwork: true
      containers:
      - name: agent
        image: logai-agent:latest
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log