# 多阶段构建Agent
FROM golang:1.21-alpine AS builder

ENV GOPROXY "https://goproxy.cn,direct"
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# 构建agent
RUN CGO_ENABLED=0 GOOS=linux go build -o agent ./cmd/agent

# 最终镜像
FROM golang:1.21-alpine
WORKDIR /app
COPY --from=builder /app/agent /app/
CMD ["/app/agent"]