apiVersion: apps/v1
kind: Deployment
metadata:
  name: logai-server
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logai-server
  template:
    metadata:
      labels:
        app: logai-server
    spec:
      nodeName: dev-master-172.10.1.11
      containers:
      - name: server
        image: logai-server:1.0.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
        volumeMounts:
        - name: data-storage
          mountPath: /data
      volumes:
      - name: data-storage
        hostPath:
          path: /home/zjx/logai-data
          type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: logai-service
  namespace: kube-system
spec:
  selector:
    app: logai-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
